/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LikedRouteImport } from './routes/liked'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as _guestRouteImport } from './routes/__guest'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TagsIdRouteImport } from './routes/tags/$id'
import { Route as PromptsIdRouteImport } from './routes/prompts/$id'
import { Route as ModelsIdRouteImport } from './routes/models/$id'
import { Route as CategoriesIdRouteImport } from './routes/categories/$id'
import { Route as _guestAuthRouteImport } from './routes/__guest/auth'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LikedRoute = LikedRouteImport.update({
  id: '/liked',
  path: '/liked',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const _guestRoute = _guestRouteImport.update({
  id: '/__guest',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsIdRoute = TagsIdRouteImport.update({
  id: '/tags/$id',
  path: '/tags/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsIdRoute = PromptsIdRouteImport.update({
  id: '/prompts/$id',
  path: '/prompts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsIdRoute = ModelsIdRouteImport.update({
  id: '/models/$id',
  path: '/models/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIdRoute = CategoriesIdRouteImport.update({
  id: '/categories/$id',
  path: '/categories/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const _guestAuthRoute = _guestAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => _guestRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/liked': typeof LikedRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/auth': typeof _guestAuthRoute
  '/categories/$id': typeof CategoriesIdRoute
  '/models/$id': typeof ModelsIdRoute
  '/prompts/$id': typeof PromptsIdRoute
  '/tags/$id': typeof TagsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/liked': typeof LikedRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/auth': typeof _guestAuthRoute
  '/categories/$id': typeof CategoriesIdRoute
  '/models/$id': typeof ModelsIdRoute
  '/prompts/$id': typeof PromptsIdRoute
  '/tags/$id': typeof TagsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/__guest': typeof _guestRouteWithChildren
  '/contact': typeof ContactRoute
  '/liked': typeof LikedRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/__guest/auth': typeof _guestAuthRoute
  '/categories/$id': typeof CategoriesIdRoute
  '/models/$id': typeof ModelsIdRoute
  '/prompts/$id': typeof PromptsIdRoute
  '/tags/$id': typeof TagsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/liked'
    | '/pricing'
    | '/privacy'
    | '/saved'
    | '/search'
    | '/terms'
    | '/auth'
    | '/categories/$id'
    | '/models/$id'
    | '/prompts/$id'
    | '/tags/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/liked'
    | '/pricing'
    | '/privacy'
    | '/saved'
    | '/search'
    | '/terms'
    | '/auth'
    | '/categories/$id'
    | '/models/$id'
    | '/prompts/$id'
    | '/tags/$id'
  id:
    | '__root__'
    | '/'
    | '/__guest'
    | '/contact'
    | '/liked'
    | '/pricing'
    | '/privacy'
    | '/saved'
    | '/search'
    | '/terms'
    | '/__guest/auth'
    | '/categories/$id'
    | '/models/$id'
    | '/prompts/$id'
    | '/tags/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  _guestRoute: typeof _guestRouteWithChildren
  ContactRoute: typeof ContactRoute
  LikedRoute: typeof LikedRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  TermsRoute: typeof TermsRoute
  CategoriesIdRoute: typeof CategoriesIdRoute
  ModelsIdRoute: typeof ModelsIdRoute
  PromptsIdRoute: typeof PromptsIdRoute
  TagsIdRoute: typeof TagsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liked': {
      id: '/liked'
      path: '/liked'
      fullPath: '/liked'
      preLoaderRoute: typeof LikedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__guest': {
      id: '/__guest'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _guestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$id': {
      id: '/tags/$id'
      path: '/tags/$id'
      fullPath: '/tags/$id'
      preLoaderRoute: typeof TagsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts/$id': {
      id: '/prompts/$id'
      path: '/prompts/$id'
      fullPath: '/prompts/$id'
      preLoaderRoute: typeof PromptsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/$id': {
      id: '/models/$id'
      path: '/models/$id'
      fullPath: '/models/$id'
      preLoaderRoute: typeof ModelsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$id': {
      id: '/categories/$id'
      path: '/categories/$id'
      fullPath: '/categories/$id'
      preLoaderRoute: typeof CategoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__guest/auth': {
      id: '/__guest/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof _guestAuthRouteImport
      parentRoute: typeof _guestRoute
    }
  }
}

interface _guestRouteChildren {
  _guestAuthRoute: typeof _guestAuthRoute
}

const _guestRouteChildren: _guestRouteChildren = {
  _guestAuthRoute: _guestAuthRoute,
}

const _guestRouteWithChildren =
  _guestRoute._addFileChildren(_guestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  _guestRoute: _guestRouteWithChildren,
  ContactRoute: ContactRoute,
  LikedRoute: LikedRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  TermsRoute: TermsRoute,
  CategoriesIdRoute: CategoriesIdRoute,
  ModelsIdRoute: ModelsIdRoute,
  PromptsIdRoute: PromptsIdRoute,
  TagsIdRoute: TagsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
